filebeat.inputs:
- type: docker
  containers:
    path: "/var/lib/docker/containers"
    ids:
      - '*'
  processors:
    - add_docker_metadata: ~
    - add_fields:
        target: ''
        fields:
          log_source: "${data.docker.container.name}"

output.file:
  path: "/var/log"
  filename: "test"
  rotate_every_kb: 10000
  number_of_files: 7

