filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    json.message_key: log
    json.keys_under_root: true
    json.add_error_key: true

processors:
  - add_docker_metadata: ~

output.file:
  path: "/var/log/test"
  filename: "container-logs.log"

logging.level: info

