version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "80:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  # Экспортёр метрик для сбора метрик из лог-сервиса (Filebeat)
  filebeat-exporter:
    build: ./filebeat-exporter
    ports:
      - "9113:9113"
    depends_on:
      - filebeat-logs

  # Сервис логов (запускается вне докера через systemd по условию)
  # но для теста здесь пример контейнера filebeat (лог-агрегатор)
  filebeat-logs:
    image: docker.elastic.co/beats/filebeat:8.7.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log/test:/var/log/test
      - ./ansible/files/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    command: filebeat -e -strict.perms=false

